package com.recycleforlife.domain;

public enum ErrorCode {
    TOKEN_EXPIRED,
    REFRESH_TOKEN_NOT_FOUND,
    LOGIN_EXISTS,
    USER_NOT_FOUND,
    JWT_MISSING,
    CATEGORY_NOT_FOUND,
    FRACTION_NOT_FOUND,
    RECEIVING_POINT_NOT_FOUND,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR
}
