version: '3.8'
services:
  p_v9:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_DATABASE=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5432:5432'
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 1s


  a_v9:
    image: kc4kt4id/recycleforlife:1.1.8
    container_name: app
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - '8080:8080'
#    depends_on:
#      postgres:
#        condition: service_healthy



########
# docker build -t recycleforlife .
# docker images
# docker tag 616c854bca63 kc4kt4id/recycleforlife:1.1.8
# docker push kc4kt4id/recycleforlife:1.1.8